[font]
normal.family = "JetbrainsMono Nerd Font"
italic.family = "JetbrainsMono Nerd Font"
size = 12.0

[window]
padding.x = 10
padding.y = 10

# decorations= "Buttonless"

opacity = 0.95
blur = true

option_as_alt = "Both"

[general]
import = [
  "~/.config/alacritty/alacritty-theme/themes/one_dark.toml"
]
